import type { DashboardStats } from '../models/Stats';
import type { Donor } from '../models/Donor';
import type { RecipientRequest } from '../models/RecipientRequest';
import type { InventoryRecord } from '../models/Inventory';
import type { DonationRecord } from '../models/Donation';
import type { Hospital } from '../models/Hospital';

export const dashboardStats: DashboardStats = {
  registeredDonors: 1840,
  livesSaved: 612,
  emergencyRequests: 12,
  activeHospitals: 48,
};

export const donors: Donor[] = [
  {
    id: 'dnr-1',
    fullName: 'Mariam Tesfaye',
    phone: '+251911000001',
    bloodType: 'O+',
    lastDonation: '2025-09-18',
    location: 'Addis Ababa, Bole',
    locationDetails: {
      region: 'Addis Ababa',
      city: 'Addis Ababa',
      subCity: 'Bole',
      woreda: 'Woreda 03',
      kebele: 'Kebele 05',
      street: 'Bole Road',
      homeNumber: '123',
    },
    latitude: 9.03,
    longitude: 38.74,
    availability: 'ready',
    totalDonations: 8,
    impactScore: 92,
  },
  {
    id: 'dnr-2',
    fullName: 'Samuel Bekele',
    phone: '+251912000002',
    bloodType: 'A-',
    lastDonation: '2025-07-02',
    location: 'Gondar',
    locationDetails: {
      region: 'Amhara',
      city: 'Gondar',
      subCity: 'Central',
      woreda: 'Woreda 01',
      kebele: 'Kebele 12',
      street: 'King Fasil Street',
      homeNumber: '45',
    },
    latitude: 12.6,
    longitude: 37.47,
    availability: 'resting',
    totalDonations: 5,
    impactScore: 74,
  },
  {
    id: 'dnr-3',
    fullName: 'Hanna Girma',
    phone: '+251913000003',
    bloodType: 'B+',
    lastDonation: '2025-10-28',
    location: 'Hawassa',
    locationDetails: {
      region: 'Sidama',
      city: 'Hawassa',
      subCity: 'Hawassa City',
      woreda: 'Woreda 02',
      kebele: 'Kebele 08',
      street: 'Lake Road',
      homeNumber: '78',
    },
    latitude: 7.06,
    longitude: 38.48,
    availability: 'ready',
    totalDonations: 3,
    impactScore: 61,
  },
];

export const requests: RecipientRequest[] = [
  {
    id: 'req-1',
    hospital: 'St. Paul Hospital',
    patient: 'Neonatal ICU',
    bloodType: 'O-',
    urgency: 'emergency',
    unitsNeeded: 4,
    status: 'pending',
    requestedAt: '2025-11-27T08:30:00Z',
  },
  {
    id: 'req-2',
    hospital: 'Black Lion Hospital',
    patient: 'Surgery Ward',
    bloodType: 'AB+',
    urgency: 'high',
    unitsNeeded: 2,
    status: 'matched',
    requestedAt: '2025-11-26T11:15:00Z',
  },
  {
    id: 'req-3',
    hospital: 'Jimma University Hospital',
    patient: 'Oncology',
    bloodType: 'A+',
    urgency: 'standard',
    unitsNeeded: 6,
    status: 'fulfilled',
    requestedAt: '2025-11-25T15:50:00Z',
  },
];

export const inventory: InventoryRecord[] = [
  { bloodType: 'O+', unitsAvailable: 42, criticalThreshold: 25, lastUpdated: '2025-11-28' },
  { bloodType: 'O-', unitsAvailable: 9, criticalThreshold: 15, lastUpdated: '2025-11-28' },
  { bloodType: 'A+', unitsAvailable: 31, criticalThreshold: 20, lastUpdated: '2025-11-28' },
  { bloodType: 'B+', unitsAvailable: 22, criticalThreshold: 18, lastUpdated: '2025-11-28' },
];

export const donationHistory: DonationRecord[] = [
  {
    id: 'hist-1',
    donorName: 'Mariam Tesfaye',
    hospital: 'St. Paul Hospital',
    bloodType: 'O+',
    units: 1,
    donationDate: '2025-10-28',
    status: 'completed',
  },
  {
    id: 'hist-2',
    donorName: 'Samuel Bekele',
    hospital: 'Black Lion Hospital',
    bloodType: 'A-',
    units: 1,
    donationDate: '2025-09-14',
    status: 'completed',
  },
  {
    id: 'hist-3',
    donorName: 'Hanna Girma',
    hospital: 'St. Peter Hospital',
    bloodType: 'B+',
    units: 1,
    donationDate: '2025-08-12',
    status: 'completed',
  },
];

export const hospitals: Hospital[] = [
  {
    id: 'hosp-1',
    name: 'Black Lion Hospital',
    phone: '+251 911 234 567',
    email: 'info@blacklion.gov.et',
    contactDoctorName: 'Dr. Alemayehu Bekele',
    contactDoctorPhone: '+251 911 234 500',
    location: 'Addis Ababa, Bole',
    locationDetails: {
      region: 'Addis Ababa',
      city: 'Addis Ababa',
      subCity: 'Bole',
      woreda: 'Woreda 03',
      kebele: 'Kebele 12',
      street: 'Bole Road',
    },
    businessLicenseName: 'Ministry of Health License',
    businessLicenseNumber: 'BLH-2024-001',
    hospitalType: 'Government Hospital',
    profilePicture: undefined,
    latitude: 9.03,
    longitude: 38.74,
  },
  {
    id: 'hosp-2',
    name: 'St. Paul Hospital',
    phone: '+251 911 234 568',
    email: 'info@stpaul.gov.et',
    contactDoctorName: 'Dr. Meseret Tadesse',
    contactDoctorPhone: '+251 911 234 501',
    location: 'Addis Ababa, Kirkos',
    locationDetails: {
      region: 'Addis Ababa',
      city: 'Addis Ababa',
      subCity: 'Kirkos',
      woreda: 'Woreda 05',
      kebele: 'Kebele 08',
      street: 'Ras Abebe Aregay Street',
    },
    businessLicenseName: 'Ministry of Health License',
    businessLicenseNumber: 'SPH-2024-002',
    hospitalType: 'Government Hospital',
    profilePicture: undefined,
    latitude: 9.01,
    longitude: 38.75,
  },
  {
    id: 'hosp-3',
    name: 'Jimma University Hospital',
    phone: '+251 911 234 569',
    email: 'info@jimma.gov.et',
    contactDoctorName: 'Dr. Tewodros Haile',
    contactDoctorPhone: '+251 911 234 502',
    location: 'Jimma',
    locationDetails: {
      region: 'Oromia',
      city: 'Jimma',
      subCity: 'Jimma City',
      woreda: 'Woreda 01',
      kebele: 'Kebele 15',
      street: 'University Road',
    },
    businessLicenseName: 'Ministry of Health License',
    businessLicenseNumber: 'JUH-2024-003',
    hospitalType: 'Government Hospital',
    profilePicture: undefined,
    latitude: 7.67,
    longitude: 36.83,
  },
];


